* %timeit for single to measure time 
* %%timeit for whole function block

In [159]:
%timeit 2+3

5.15 ns ± 0.0271 ns per loop (mean ± std. dev. of 7 runs, 100000000 loops each)


In [162]:
%%timeit
l = []
for i in range(1,4):
    l.append(i**2)


563 ns ± 22.8 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


### Numpy
** NumPy really fast compare to ordinary python lists
* 1-d array - vector
* 2-d array - matrix
* n-d array tensor

In [24]:
import numpy as np

In [25]:
nums = [1,2,3,4]                # vecctor
nums1 = [[1,2,3],[4,5,6]]       # matrix
nums2 = [[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]]

In [30]:
n = np.array(nums)
n

array([1, 2, 3, 4])

In [31]:
n1 = np.array(nums1)
n1

array([[1, 2, 3],
       [4, 5, 6]])

In [32]:
n2 = np.array(nums2)
n2

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

In [29]:
# to check the dimension - ndim
n2.ndim

3

In [34]:
n2.shape   # 3 dim -- block size, row, col size

(2, 2, 3)

### Zeros, ones,eye - (identity matrix) , diag, randint, rand, randn

In [35]:
arr = np.zeros(5)
arr

array([0., 0., 0., 0., 0.])

In [37]:
arr1 = np.zeros((2,3))    # 2,3 matrix 
arr1

array([[0., 0., 0.],
       [0., 0., 0.]])

In [39]:
arr2 = np.ones((3,2,3))
arr2

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [40]:
# eye--> identity matrix 
arr3 = np.eye(4)
arr3

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [41]:
# diag --list(represent in the diagonal) making square matrix 
arr = np.diag([1,5,9,7])
arr

array([[1, 0, 0, 0],
       [0, 5, 0, 0],
       [0, 0, 9, 0],
       [0, 0, 0, 7]])

In [45]:
# rand
rand_arr = np.random.randint(1,15,5)
rand_arr

array([ 2,  3,  5, 11,  7])

In [46]:
# randn   --> it can generate normal distributed number considering 0 as center
randn_arr = np.random.randn(10)
randn_arr

array([-0.56121407,  1.14699434, -0.95050277, -0.78942269, -1.13004314,
       -0.57542058, -2.13329496, -0.9508957 ,  0.39732028, -0.42372532])

## Reshaping of Data
* Reshape
* reshape(n,-1) now -1 automatically calculate what size of array they have eg - 20   reshape(2,-1) then -->(2,10)

In [49]:
arr = np.random.randint(1,100,20)
arr

array([88, 38, 30, 67, 54,  3, 72, 10, 70, 63, 34, 23, 86, 99, 82, 41, 92,
       45, 25, 25])

In [51]:
arr.shape

(20,)

In [52]:
# in above it show it is 1D array  convert into 2D array
arr = arr.reshape(4,5)
arr

array([[88, 38, 30, 67, 54],
       [ 3, 72, 10, 70, 63],
       [34, 23, 86, 99, 82],
       [41, 92, 45, 25, 25]])

In [53]:
arr.ndim

2

* To generate the fix random number 

In [64]:
np.random.seed(1)
arr = np.random.randint(1,101,20)
arr

array([38, 13, 73, 10, 76,  6, 80, 65, 17,  2, 77, 72,  7, 26, 51, 21, 19,
       85, 12, 29])

In [65]:
arr.size

20

In [69]:
updated_arr = arr.reshape(4,-1)
updated_arr

array([[38, 13, 73, 10, 76],
       [ 6, 80, 65, 17,  2],
       [77, 72,  7, 26, 51],
       [21, 19, 85, 12, 29]])

In [72]:
updated_arr[:2,:3]

array([[38, 13, 73],
       [ 6, 80, 65]])

In [73]:
updated_arr[1:3,2:4]

array([[65, 17],
       [ 7, 26]])

### View vs copy array
* copy --> In this case the changes not affect the main array
* view(=)--> In this case changes may affected the main array

In [75]:
arr

array([38, 13, 73, 10, 76,  6, 80, 65, 17,  2, 77, 72,  7, 26, 51, 21, 19,
       85, 12, 29])

In [77]:
sliced_arr = arr[3:6]
sliced_arr

array([10, 76,  6])

In [78]:
# In this case they shared the main memory location ----> view

sliced_arr[:]=0
sliced_arr

array([0, 0, 0])

### Base - is used check either this view or copy
* copy - return none
* view - return main array

In [91]:
print(sliced_arr.base)

[38 13 73  0  0  0 80 65 17  2 77 72  7 26 51 21 19 85 12 29]


In [79]:
arr

array([38, 13, 73,  0,  0,  0, 80, 65, 17,  2, 77, 72,  7, 26, 51, 21, 19,
       85, 12, 29])

**Copy()

In [81]:
cparry = arr[9:13].copy()
cparry

array([ 2, 77, 72,  7])

In [82]:
cparry[:]=0
cparry

array([0, 0, 0, 0])

In [89]:
print(cparry.base)

None


In [83]:
arr

array([38, 13, 73,  0,  0,  0, 80, 65, 17,  2, 77, 72,  7, 26, 51, 21, 19,
       85, 12, 29])

### Conditional 


In [92]:
arr >5

array([ True,  True,  True, False, False, False,  True,  True,  True,
       False,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True])

In [96]:
arr[arr>5]

array([38, 13, 73, 80, 65, 17, 77, 72,  7, 26, 51, 21, 19, 85, 12, 29])

In [97]:
np.random.seed(51)
matrix1 = np.random.randint(1,12,9).reshape(3,3)
matrix2 = np.random.randint(5,15,9).reshape(3,3)

print(matrix1 * matrix2)

[[100  60   9]
 [ 90  48  11]
 [ 54  55 140]]


In [98]:
print(matrix1.dot(matrix2))

[[163 159 170]
 [163 159 170]
 [195 210 249]]


In [99]:
arr.min()

0

In [100]:
arr.max()

85

In [101]:
np.argmin(arr)

3

* Linspace --> equal space number return 

In [103]:
np.linspace(1,15,50)

array([ 1.        ,  1.28571429,  1.57142857,  1.85714286,  2.14285714,
        2.42857143,  2.71428571,  3.        ,  3.28571429,  3.57142857,
        3.85714286,  4.14285714,  4.42857143,  4.71428571,  5.        ,
        5.28571429,  5.57142857,  5.85714286,  6.14285714,  6.42857143,
        6.71428571,  7.        ,  7.28571429,  7.57142857,  7.85714286,
        8.14285714,  8.42857143,  8.71428571,  9.        ,  9.28571429,
        9.57142857,  9.85714286, 10.14285714, 10.42857143, 10.71428571,
       11.        , 11.28571429, 11.57142857, 11.85714286, 12.14285714,
       12.42857143, 12.71428571, 13.        , 13.28571429, 13.57142857,
       13.85714286, 14.14285714, 14.42857143, 14.71428571, 15.        ])

In [106]:
np.array([1,0,5,9], dtype ='bool' )

array([ True, False,  True,  True])

* Numpy -- axis 0 -> Columns
* axis 1 -> for row

In [115]:
new_arr = arr.reshape(4,-1).copy()
new_arr

array([[38, 13, 73,  0,  0],
       [ 0, 80, 65, 17,  2],
       [77, 72,  7, 26, 51],
       [21, 19, 85, 12, 29]])

In [118]:
np.max(new_arr, axis = 0) # give max 

array([77, 80, 85, 26, 51])

In [119]:
np.max(new_arr, axis = 1) # row wise

array([73, 80, 77, 85])

In [120]:
np.sum(new_arr, axis = 0)    # col wise 

array([136, 184, 230,  55,  82])

#### Suffle and unique

In [127]:
np.random.seed(123)
arrn = np.random.randint(1,15,15)
arrn


array([14,  3, 13,  3,  7,  2,  4, 11, 12, 10,  7,  2,  1,  2, 10])

In [128]:
np.random.shuffle(arrn)

In [129]:
np.unique(arrn)

array([ 1,  2,  3,  4,  7, 10, 11, 12, 13, 14])

In [130]:
np.unique(arrn, return_index = True, return_counts = True )

(array([ 1,  2,  3,  4,  7, 10, 11, 12, 13, 14]),
 array([ 8,  1,  6,  0,  7, 12,  2,  3,  4, 14]),
 array([1, 3, 2, 1, 2, 2, 1, 1, 1, 1]))

### horizonatal and vertical stacking
* hstack
* vstack

In [134]:
matrix1 = np.random.randint(1,20,9).reshape(3,3)
matrix2 = np.random.randint(21,80,9).reshape(3,3)
print(matrix1)
matrix2

[[ 8  2 12]
 [ 6 19 18]
 [13 19 18]]


array([[22, 72, 65],
       [74, 62, 69],
       [77, 48, 70]])

In [136]:
np.hstack((matrix1,matrix2))

array([[ 8,  2, 12, 22, 72, 65],
       [ 6, 19, 18, 74, 62, 69],
       [13, 19, 18, 77, 48, 70]])

In [137]:
np.vstack((matrix1,matrix2))

array([[ 8,  2, 12],
       [ 6, 19, 18],
       [13, 19, 18],
       [22, 72, 65],
       [74, 62, 69],
       [77, 48, 70]])

In [140]:
import numpy as np

np.array([[1,2,3],[4,5,6]])

array([[1, 2, 3],
       [4, 5, 6]])

In [151]:
np.arange(20,40)

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36,
       37, 38, 39])

In [142]:
np.random.randint(20,40,20)

array([23, 31, 27, 29, 22, 23, 31, 23, 39, 26, 29, 34, 26, 39, 26, 32, 26,
       37, 34, 30])

In [148]:
a = np.random.randint(1,10,10)
a[:] = 0
print(a)

[0 0 0 0 0 0 0 0 0 0]


In [153]:
np.random.randint(20,80,20).reshape(2,5,2)

array([[[27, 58],
        [44, 26],
        [33, 48],
        [64, 40],
        [56, 75]],

       [[68, 52],
        [77, 60],
        [44, 72],
        [78, 78],
        [65, 33]]])

In [156]:
print(np.random.rand(25))
print(np.random.rand(4,5))

[0.25754206 0.56435904 0.80696868 0.39437005 0.73107304 0.16106901
 0.60069857 0.86586446 0.98352161 0.07936579 0.42834727 0.20454286
 0.45063649 0.54776357 0.09332671 0.29686078 0.92758424 0.56900373
 0.457412   0.75352599 0.74186215 0.04857903 0.7086974  0.83924335
 0.16593788]
[[0.78099794 0.28653662 0.30646975 0.66526147 0.11139217]
 [0.66487245 0.88785679 0.69631127 0.44032788 0.43821438]
 [0.7650961  0.565642   0.08490416 0.58267109 0.8148437 ]
 [0.33706638 0.92757658 0.750717   0.57406383 0.75164399]]


In [158]:
arr5 = np.random.seed(123)
arr = np.random.randint(1,50,20)
arr[arr%2==0] = -1
arr

array([-1,  3, 29, 35, 39, -1, -1, 43, 23, -1, 33, -1, -1, 33, 47, 33, -1,
       -1, -1, 15])